# Generated by Django 2.2 on 2020-05-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0004_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
